apiVersion: vk8s.sktelecom.com/v1alpha1
kind: Vk8s
metadata:
  annotations:
    cluster-network-connection-status: "true"
  name: vk8s-1-21-ubuntu
spec:
  nodes:
  - name: vk8s-1-21-ubuntu-node-0
    tolerations:
    - key: scale/node.type
      operator: Equal
      effect: NoSchedule
      value: IAAS
    image: 223.62.245.134:5001/scale/workflow/vk8s/kink:v1.21-ubuntu
    role: master
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "8"
        memory: "10Gi"
  kubeflow:
    version: v1.5.0
    email: test@skt.com
    password: test!!22
  ports:
  - name: kubeflow
    port: 30002
    targetPort: 30002
