## HAVE TO ADD
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: pipeline-add-header
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: ml-pipeline.kubeflow.svc.cluster.local:8888
          route:
            name: default
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: true
          header:
            key: kubeflow-userid
            value: email
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: bind-kfp-proxyb
spec:
 selector:
   matchLabels:
     app: kfp-proxy
 action: ALLOW
 rules:
  - to:
    - operation:
        methods: ["*"]

