apiVersion: vk8s.skt.co.kr/v1alpha1
kind: Vk8s
metadata:
  name: sample2
spec:
  browserPort: 30001
  nodes:
  - name: sample-master2
    image: dudaji/kink:v1.19
    role: master
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "16"
        memory: "30Gi"
  - name: sample-worker2
    image: dudaji/kink:v1.19
    role: worker
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "16"
        memory: "30Gi"
  nfsServer: test.synology.me
  nfsMountPath: /volume1/test
  kubeflow: false
