# permissions for end users to edit vk8s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vk8s-editor-role
rules:
- apiGroups:
  - vk8s.skt.co.kr
  resources:
  - vk8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vk8s.skt.co.kr
  resources:
  - vk8s/status
  verbs:
  - get
